name: Auto Sync Repo

# Trigger on every push to 'main' and every 5 minutes.
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

# IMPORTANT: Grant write permission so the workflow can push changes.
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit & Push Changes
        run: |
          git add .
          git commit -m "Auto update from GitHub Action" || echo "No changes to commit"
          git push origin main
