name: Auto Sync Repo

on:
  push:
    branches:
      - main  # Change to your branch if needed
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit & Push Changes
        run: |
          git add .
          git commit -m "Auto update from GitHub Action" || echo "No changes to commit"
          git push origin main
